const styles = {
    main: {
        container: 'relative flex flex-col min-h-screen bg-red-100',
    },
    navbar: {
      container: 'fixed w-full max-w-[1440px] bg-white flex justify-between items-center leading-normal py-4 px-3 md:px-12 border-b border-blue-300 z-100',
      logo: 'text-blue-700 text-xl font-bold flex flex-row space-x-6 items-center',
    logoText: 'text-xl font-bold text-blue-700',
      navLinks: 'hidden md:flex space-x-4',
      link: 'text-md mt-2 px-1 font-normal text-gray-700 hover:text-gray-400 transition duration-300 ease-in-out',
      button: "bg-blue-800 text-gray-50 px-4 py-2 rounded-md hover:bg-blue-700 transition duration-300 ease-in-out",
      logoImg: 'h-[50px] w-[50px] object-center object-cover rounded-lg shadow-lg',
    },
    mobileMenu: {
        container: 'md:hidden relative top-0 right-0 z-50 h-[73px] w-[80px]', 
        containerActive: '', 
        panel: 'fixed top-[80px] right-0 h-screen w-2/3 max-w-xs bg-white shadow-lg transition-transform duration-300 transform translate-x-full',
        panelActive: '!translate-x-0',
        button: 'absolute top-4 right-4 p-2 z-100',
        btn: 'inline-flex justify-start my-4 w-full rounded-md border border-none px-1  bg-white text-md font-medium text-gray-700 hover:text-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500',
        icon: 'h-6 w-6',
        navLinks: 'w-full flex flex-col items-start px-6 space-y-4',
        listItem: 'w-full',
    },
    footer: {
        container: 'w-full bg-blue-800 p-4 border-t border-blue-300',
        content: 'flex justify-between items-center',
        text: 'text-gray-100 text-sm',
        socialIcons: 'flex flex-row space-x-4',
        icon: 'text-gray-100 hover:text-gray-400 transition duration-300 ease-in-out',
        policyContent: 'mt-[73px] px-40 flex flex-col flex-1 justify-center overflow-y-auto',
        title: 'text-3xl font-bold text-center text-blue-800 mb-8',
        description: 'mt-4 text-lg text-start text-gray-600 leading-7',
        button: "bg-blue-800 text-gray-50 px-4 py-2 rounded-md hover:bg-blue-700 transition duration-300 ease-in-out",
    },
    dropdown: {
        container: 'relative inline-block text-left',
        button: 'inline-flex justify-center mt-2 w-full rounded-md border border-none px-1  bg-white text-md font-medium text-gray-700 hover:text-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500',
        menu: 'absolute right-0 z-10 mt-2 w-48 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none max-h-60 overflow-y-auto',
        item: 'block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100',
        itembtn: 'block w-full text-sm text-start text-gray-700 hover:bg-gray-100',
        arrow: 'ml-2',
    },
    hero: {
        container: 'relative mt-[73px] flex flex-col items-center justify-center h-[400px] md:h-fit bg-gray-100',
        shade: 'w-full h-full absolute inset-0 bg-black opacity-20',
        subcontainer: 'absolute z-10 w-fit flex flex-col items-center justify-center w-full max-w-2xl mx-auto text-center px-8 rounded-lg shadow-lg',
        subshade: 'w-full h-full absolute inset-0 bg-gradient-to-r from-gray-200 via-gray-800 to-gray-200 opacity-50 z-1 rounded-lg',
        content: 'relative z-10 flex flex-col items-center justify-center w-full max-w-2xl mx-auto text-center p-8 rounded-lg',
        title: 'text-4xl font-bold bg-gradient-to-r from-blue-500 to-gray-100 bg-clip-text text-transparent',
        img: 'w-full h-[400px] md:h-[540px] object-center object-cover z--1',
        description: 'mt-4 text-lg text-gray-200',
        text: 'text-center text-gray-700',
        subtext: 'text-center text-gray-600',
        subtitle: 'mt-2 text-lg text-gray-00',
        button: 'mt-4 bg-blue-800 w-[260px] text-white px-4 py-2 rounded-md hover:bg-gray-700 transition duration-300 ease-in-out',
    },
    service: {
        container: 'w-full bg-white p-8',
        title: 'text-3xl font-bold text-center text-blue-800 mb-8',
        flex: 'flex flex-wrap justify-center items-center space-x-4',
        card: 'bg-white shadow-lg rounded-lg p-6 m-4 w-[300px] h-[200px] flex flex-col',
        cardTitle: 'text-xl font-semibold text-blue-800',
        cardDescription: 'text-gray-600 mt-2 items-start',
        hoverEffect: 'hover:shadow-blue-400 transition duration-300 ease-in-out',
    },
    about: {
        container: 'w-full bg-gray-100 p-8',
        title: 'text-3xl font-bold text-center text-blue-800 mb-8',
        subcontainer: 'flex flex-col md:flex-row items-center justify-center space-x-4 px-3 md:px-10',
        img: 'w-full h-auto md:h-[340px] object-center object-cover rounded-lg shadow-lg',
        content: 'flex flex-col items-start justify-start w-full max-w-2xl mx-auto text-left p-8 rounded-lg shadow-lg',
        description: 'mt-4 text-md md:text-lg text-gray-600',
    },
    aboutme: {
        container: 'w-full my-20 bg-white p-8',
        title: 'text-3xl font-bold text-center text-gray-800 mb-8',
        subcontainer: 'flex flex-col-reverse md:flex-row items-center justify-center space-x-4 px-3 md:px-10',
        img: 'w-[400px] h-auto object-center object-cover rounded-lg shadow-lg',
        content: 'flex flex-col items-start justify-start w-full max-w-2xl mx-auto text-left p-8 rounded-lg shadow-lg',
        description: 'mt-4 text-md md:text-lg text-gray-600',
        highlight: 'text-blue-800 font-bold',
    },
    contact: {
        container: 'w-full bg-gray-100 p-8',
        title: 'text-3xl font-bold text-center text-blue-800 mb-8',
        subcontainer: 'flex flex-col md:flex-row items-center justify-between space-x-4 px-3 md:px-20',
        leftside: 'flex flex-col w-full max-w-md mx-auto',
        rightside: 'flex flex-col w-full max-w-md mx-auto',
        subtitle: 'text-2xl text-center font-bold text-blue-800 mb-4',
        text: 'text-lg text-center text-gray-600 mb-2',
        description: 'mt-4 text-lg text-gray-600',
        button: 'mt-4 bg-blue-800 w-[260px] text-white px-4 py-2 rounded-md hover:bg-gray-700 transition duration-300 ease-in-out',
        img: 'hidden md:block w-[550px] h-[540px] object-left object-cover rounded-lg shadow-lg',
    },
    form: {
        container: 'w-full p-8',
        title: 'text-3xl font-bold text-center text-blue-800 mb-8',
        subcontainer: 'flex flex-col md:flex-col items-center justify-center space-x-4',
        leftside: 'flex flex-col w-full max-w-md mx-auto',
        rightside: 'mt-5 flex flex-col w-full max-w-md mx-auto',
        input: 'border border-gray-300 rounded-md p-2 mb-4',
        textarea: 'border border-gray-300 rounded-md p-2 mb-4 h-[200px]',
        button: 'bg-blue-800 text-white px-4 py-2 rounded-md hover:bg-gray-700 transition duration-300 ease-in-out',
        description: 'mt-4 text-lg text-green-600',
    },
    insurers: {
        container: 'w-full mt-20 bg-white p-8 overflow-x-hidden',
        subcontainer: 'w-5/6 mx-auto overflow-x-hidden',
        title: 'text-3xl font-bold text-center text-blue-800 mb-8',
        header: 'flex flex-col items-center justify-center space-x-4',
        content: 'flex flex-col items-start justify-start w-full max-w-2xl mx-auto text-left p-8 rounded-lg shadow-lg',
        question: 'mt-4 text-lg text-gray-600',
        answer: 'mt-2 text-md text-gray-500',
        description: 'mt-4 text-lg text-gray-600',
        carousel: 'w-5/6 mx-auto flex justify-center items-center space-x-4',
        img: 'w-auto h-[200px] object-center object-cover rounded-lg shadow-lg',
        card: 'w-fit h-fit',
    },
    joinUs: {
        container: 'w-full bg-white p-8',
        title: 'text-3xl font-bold text-center text-blue-800 mb-8',
        subcontainer: 'flex flex-col md:flex-row items-center justify-center space-x-4',
        content: 'flex flex-col items-start justify-start w-full max-w-2xl mx-auto text-left p-8 rounded-lg shadow-lg',
        description: 'mt-4 text-lg text-center text-gray-600',
    },
    modal: {
        backdrop: "fixed inset-0 bg-black/50 flex items-center justify-center z-50 ",
        container: "bg-white rounded-2xl shadow-xl p-6 w-full max-w-lg"
    },
    quoteForm: {
        container: 'w-full p-8',
        title: 'text-3xl font-bold text-center text-blue-800 mb-8',
        subcontainer: 'flex flex-col md:flex-row items-center justify-center space-x-4',
        inputGroup: 'flex flex-row w-full max-w-md mx-auto justify-between',
        input: 'border border-gray-300 rounded-md p-2 mb-4',
        textarea: 'border border-gray-300 rounded-md p-2 mb-4 h-[200px]',
        button: 'bg-blue-800 text-white px-4 py-2 rounded-md hover:bg-gray-700 transition duration-300 ease-in-out',
        description: 'mt-4 text-lg text-green-600',
    },
    card: {
        container: 'w-full p-3 md:p-20 flex justify-between items-center px-3 md:px-40',
        flexRow: 'flex-col-reverse md:flex-row',
        flexRowReverse: 'flex-col-reverse md:flex-row-reverse',
        imageContainer: 'flex items-center',
        image: 'h-[200px] w-fit object-center object-cover rounded-lg shadow-lg',
        content: 'max-w-[500px]',
        title: 'text-2xl md:text-3xl font-bold text-start text-blue-800 mb-8',
        description: 'mt-4 text-md md:text-lg text-gray-800',
        subcontainer: 'absolute z-10 w-fit flex flex-col items-center justify-center w-full max-w-2xl mx-auto text-center px-8 rounded-lg',
    }
  }
  
  export default styles
  